// src/strings.js — 双语文案数据块（STR；LOCALE 由 navigator.language 推导，仅此处使用）。
// 由 lib/client.js 拆出（2026-09-13，客户端源码模块化；适配发布审查的单文件体积上限）。
// 构建链：npm run build:client（esbuild 打包压缩为 lib/client.js，factory 契约不变）。
// ⚠️ 本文件是源码，不直接运行——运行时只加载 lib/client.js 产物；改动后必须重新构建。

  let LOCALE = 'en'
  try {
    const nl = String(navigator.language || navigator.userLanguage || '')
    if (nl.toLowerCase().startsWith('zh')) LOCALE = 'zh'
  } catch (e) {}

  const STR = LOCALE === 'zh' ? {
    entry: '会话流', title: '会话流', rescan: '重新扫描', scanning: '扫描中…',
    pianoTitle: '轮次', pianoNew: '新建会话', pianoFav: '收藏', pianoUnfav: '取消收藏', pianoFavs: '收藏', pianoOpenInFlow: '在会话流中打开',
    pianoJumpFail: '该轮次尚未加载：请在会话区向上滚动加载历史后再点击',
    fullText: '全文检索', fullTextSearching: '搜索中…', fullTextPartial: '已扫描 {N}/{M} 个会话（结果未完整）', fullTextNone: '全文无命中', fullTextFail: '全文检索失败',
    dock: '并入右栏', dockExit: '退出并入', dockHint: '会话流已并入右侧栏 · 随当前会话切换', dockEmpty: '打开会话后可在此查看会话流',
    dockLiveHint: '实时：只显示开播后的对话，不加载历史回合', dockLiveEmpty: '实时中 · 等待新对话…', dockLiveEnterFail: '当前会话已结束或不可实时',
    dockPinNotice: '📌 直播已钉住原会话（当前已切换会话）', dockPinRebind: '转播当前会话',
    rename: '重命名', renamePlaceholder: '输入新标题…', renameFail: '重命名失败', origTitle: '原名',
    search: '搜索标题/工具/文件… 支持 tool: pwsh · file: src · err:', allWorkspaces: '全部工作区',
    sortRecent: '最近运行', sortNewest: '最近创建', sortOldest: '最早创建', sortTools: '工具最多', sortLongest: '耗时最长', sortSize: '占用最大',
    noMatch: '没有匹配的会话', noData: '暂无会话数据',
    running: '进行中', ended: '已结束', subagent: '子代理',
    turns: '回合', steps: '步骤', tools: '工具', errors: '错误', msgs: '消息',
    duration: '耗时', created: '创建', size: '大小', records: '记录',
    jumpFailed: '无法跳转（会话不在当前列表）', unknownTitle: '（未命名会话）',
    loadFailed: '加载失败',
    back: '返回', openWorkbench: '打开完整工作台', close: '关闭', jumpNative: '跳转原生会话', expandAll: '全部展开', collapseAll: '全部折叠',
    exportMd: '导出报告 (ZIP)', exporting: '导出中…', exportFail: '导出失败',
    live: '实时', liveActive: '实时 · 进行中', liveExit: '退出实时', liveLoading: '实时加载…',
    liveFail: '实时不可用', liveUnavailable: '（实时通道不可用：连接不可用）',
    liveFallbackHint: '会话尚未落盘 · 实时视图（3s 轮询）', retryArchive: '重试档案视图',
    liveEvents: '事件', liveRefreshing: '刷新…', liveLastActive: '最后活动',
    liveTurn: '运行中', liveGenerating: '正在生成…',
    detailLoading: '正在解析会话…', noTimeline: '无可展示的时间线', artifacts: '产物',
    noArtifacts: '（未提取到产物路径）', user: '用户', assistant: '助手', step: '步骤',
    args: '参数', result: '结果', thinking: '思考', expanded: '展开', collapsed: '收起',
    detailFailed: '会话详情加载失败', showEmpty: '显示空会话', emptySession: '空会话',
    emptyHint: '此会话已创建但尚未开始对话', userNav: '用户发言', noUserNav: '（无用户发言）',
    conclusion: '结论', injected: '注入', lineage: '血缘', noLineage: '（无子代理血缘信息）', task: '任务',    liveTree: '运行时血缘', offlineTree: '档案血缘', modeOneShot: '一次性', modeContinuable: '可续',
    subagentDetail: '子代理详情', loadDetail: '加载子代理详情…', noDetail: '该子代理无可见事件',
    viewSubagent: '查看子代理', toolTop: '工具 Top', issues: '问题会话', issuesHint: '只显示有错误记录的会话', storage: '存储', storageHint: '当前范围会话存档总占用（只读）',
    searchTab: '检索', searchInPlaceholder: '会话内检索…', noMatches: '无匹配位置', matches: '命中', navUsers: '用户',
    cache: '缓存管理', cacheTotal: '缓存总量', cacheIndex: '会话索引', cacheTimeline: '时间线缓存',
    cleanTimeline: '清理时间线缓存', cleanAll: '清理全部缓存', cacheDone: '已清理', cacheEmpty: '（无缓存文件）',
    summary: '会话摘要', summaryGoal: '首个任务', summaryConclusion: '最近结论', summaryTools: '工具',
    summaryTaskCount: '任务数', summaryProvisional: '（可能仅为当前进展）',
    summaryStale: '⚠ 摘要生成后有新对话，内容可能已不准确，建议重新生成',
    llmSummary: '生成 LLM 摘要', llmGenerating: '生成中…', llmFail: '生成失败', summaryRuleTag: '规则', summaryLlmTag: 'LLM',
    cacheHint: '仅清理本插件的缓存（可自动重建），不影响 DSH 会话存档与任何其他数据', cacheLimit: '时间线缓存上限',
    healthActive: '活跃', healthToolWait: '工具执行中', healthQuiet: '静默中', healthStalled: '疑似卡死', healthIdle: '空闲',
    agoJustNow: '刚刚', agoMin: '{N} 分钟前', agoHour: '{N} 小时前', agoDay: '{N} 天前',
    healthSilentMin: '静默 {N} 分钟', healthSilentSec: '静默 {N} 秒',
    healthChipTitle: '会话健康状态（会话流）· 点击打开详情',
    renameClearBlocked: '该会话标题由官方会话管理：请输入新标题（不支持清空）',
    settingsTitle: '会话流', settingsDesc: '调整轮次导航、实时跟踪与健康监控的行为参数。保存后立即生效（轮次悬浮条行数在重进会话页后完全生效）。',
    setGroupPiano: '轮次悬浮条', setGroupLive: '实时跟踪', setGroupHealth: '健康监控', setGroupNav: '轮次导航（v0.1.2+）',
    setPianoWindow: '可见行数', setPianoWindowHint: '悬浮条同时显示的轮次条数（6–18）',
    setPianoWheelSpeed: '滚轮灵敏度', setPianoWheelSpeedHint: '每像素滚动的行数（0.005–0.03），越大滚得越快',
    setPianoSnapMs: '静止吸附延迟（ms）', setPianoSnapMsHint: '滚轮停止多少毫秒后吸附到整行（100–400）',
    setLivePollMs: '轮询间隔（ms）', setLivePollMsHint: '实时模式的刷新间隔（1500–10000），下次开播生效',
    setLiveFollowPx: '吸底阈值（px）', setLiveFollowPxHint: '距底部多少像素内视为「在底部」并跟随滚动（20–120）',
    setLiveHistoryTurns: '保留历史回合', setLiveHistoryTurnsHint: '实时模式下保留的历史回合数（0–10），下次开播生效',
    setStallThresholdMin: '卡死阈值（分钟）', setStallThresholdMinHint: '运行中但静默超过该时长判定为疑似卡死（1–10）',
    setRailEnhance: '官方轮次导航增强', setRailEnhanceHint: '在官方右侧轮次导航上叠加：预览卡内追加结论摘要、右键唤起工作台',
    setPianoClassic: '经典左侧悬浮条', setPianoClassicHint: '插件自带的左侧轮次悬浮条（默认开，与官方右侧导航并存；点击未载入轮次可委托官方引擎自动加载跳转）',
    setRailHide: '隐藏官方轮次导航', setRailHideHint: '完全屏蔽官方右侧刻度条，只保留我们的悬浮条（开启后「官方轮次导航增强」自动不生效）',
    railMetaCalls: '{tools} 次工具', railMetaErrors: '{errors} 错误', railThinking: '含思考',
    setSave: '保存', setDiscard: '放弃更改', setSaveFail: '部分设置未保存成功，请检查后重试',
    setReset: '恢复默认', setOverridden: '已修改', setInvalid: '超出范围或格式无效',
    setUnavailable: '当前环境未暴露设置服务，无法编辑（请升级 dsh 后重试）',
  } : {
    entry: 'Session Flow', title: 'Session Flow', rescan: 'Rescan', scanning: 'Scanning…',
    pianoTitle: 'Turns', pianoNew: 'New session', pianoFav: 'Favorite', pianoUnfav: 'Unfavorite', pianoFavs: 'Favorites', pianoOpenInFlow: 'Open in Session Flow',
    pianoJumpFail: 'Turn not loaded — scroll up in the conversation to load history, then retry',
    fullText: 'Full-text', fullTextSearching: 'Searching…', fullTextPartial: 'Scanned {N}/{M} sessions (partial)', fullTextNone: 'No full-text matches', fullTextFail: 'Full-text search failed',
    dock: 'Dock right', dockExit: 'Undock', dockHint: 'Session Flow docked · follows current session', dockEmpty: 'Open a session to view its flow here',
    dockLiveHint: 'Live: only the conversation since enabled, no history', dockLiveEmpty: 'Live · waiting for new turns…', dockLiveEnterFail: 'Session ended or not live-capable',
    dockPinNotice: '📌 Live pinned to previous session (session switched)', dockPinRebind: 'Follow current session',
    rename: 'Rename', renamePlaceholder: 'New title…', renameFail: 'Rename failed', origTitle: 'Original',
    search: 'Search title / tools / files… use tool: · file: · err:', allWorkspaces: 'All workspaces',
    sortRecent: 'Recently run', sortNewest: 'Recently created', sortOldest: 'Oldest first', sortTools: 'Most tools', sortLongest: 'Longest', sortSize: 'Largest',
    noMatch: 'No matching sessions', noData: 'No session data yet',
    running: 'Running', ended: 'Ended', subagent: 'subagent',
    turns: 'turns', steps: 'steps', tools: 'tools', errors: 'errors', msgs: 'msgs',
    duration: 'duration', created: 'created', size: 'size', records: 'records',
    jumpFailed: 'Cannot open (session not in live list)', unknownTitle: '(untitled session)',
    loadFailed: 'Load failed',
    back: 'Back', openWorkbench: 'Open workbench', close: 'Close', jumpNative: 'Open in native view', expandAll: 'Expand all', collapseAll: 'Collapse all',
    exportMd: 'Export report (ZIP)', exporting: 'Exporting…', exportFail: 'Export failed',
    live: 'Live', liveActive: 'Live · running', liveExit: 'Exit live', liveLoading: 'Loading live…',
    liveFail: 'Live unavailable', liveUnavailable: '(live channel unavailable: no connection)',
    liveFallbackHint: 'Session not persisted yet · live view (3s poll)', retryArchive: 'Retry archive view',
    liveEvents: 'events', liveRefreshing: 'refreshing…', liveLastActive: 'last active',
    liveTurn: 'Running', liveGenerating: 'Generating…',
    detailLoading: 'Parsing session…', noTimeline: 'No timeline to show', artifacts: 'Artifacts',
    noArtifacts: '(no artifact paths extracted)', user: 'User', assistant: 'Assistant', step: 'Step',
    args: 'Args', result: 'Result', thinking: 'Thinking', expanded: 'Expanded', collapsed: 'Collapsed',
    detailFailed: 'Failed to load session detail', showEmpty: 'Show empty sessions', emptySession: 'Empty',
    emptyHint: 'This session was created but has no conversation yet', userNav: 'User turns', noUserNav: '(no user turns)',
    conclusion: 'Conclusion', injected: 'Injected', lineage: 'Lineage', noLineage: '(no subagent lineage)', task: 'Task',
    liveTree: 'Live lineage', offlineTree: 'Archive lineage', modeOneShot: 'one-shot', modeContinuable: 'continuable',
    subagentDetail: 'Subagent detail', loadDetail: 'Loading subagent detail…', noDetail: 'No visible events for this subagent',
    viewSubagent: 'View subagent', toolTop: 'Tool Top', issues: 'Problem sessions', issuesHint: 'Only sessions with errors', storage: 'Storage', storageHint: 'Total archive size of sessions in scope (read-only)',
    searchTab: 'Search', searchInPlaceholder: 'Search in session…', noMatches: 'No matches', matches: 'matches', navUsers: 'User',
    cache: 'Cache Mgmt', cacheTotal: 'Cache total', cacheIndex: 'Index', cacheTimeline: 'Timeline cache',
    cleanTimeline: 'Clean timeline cache', cleanAll: 'Clean all cache', cacheDone: 'Cleaned', cacheEmpty: '(no cache files)',
    summary: 'Session summary', summaryGoal: 'First task', summaryConclusion: 'Latest result', summaryTools: 'Tools',
    summaryTaskCount: 'Tasks', summaryProvisional: '(may only be current progress)',
    summaryStale: '⚠ New conversation since summary was generated; content may be outdated — regenerate',
    llmSummary: 'Generate LLM summary', llmGenerating: 'Generating…', llmFail: 'Failed', summaryRuleTag: 'rule', summaryLlmTag: 'LLM',
    cacheHint: "Only this plugin's cache (auto-rebuilds); never touches DSH session archives or other data", cacheLimit: 'Timeline cache limit',
    healthActive: 'Active', healthToolWait: 'Tool running', healthQuiet: 'Quiet', healthStalled: 'Likely stalled', healthIdle: 'Idle',
    agoJustNow: 'just now', agoMin: '{N}m ago', agoHour: '{N}h ago', agoDay: '{N}d ago',
    healthSilentMin: 'silent {N} min', healthSilentSec: 'silent {N} s',
    healthChipTitle: 'Session health (Session Flow) · click to open detail',
    renameClearBlocked: 'Title is managed by the official session: enter a new title (clearing unsupported)',
    settingsTitle: 'Session Flow', settingsDesc: 'Tune turn navigation, live-tracking, and health-monitor behavior. Applies on save (strip row count fully applies after re-entering a session page).',
    setGroupPiano: 'Turn strip', setGroupLive: 'Live tracking', setGroupHealth: 'Health monitor', setGroupNav: 'Turn navigation (v0.1.2+)',
    setPianoWindow: 'Visible rows', setPianoWindowHint: 'How many turn keys the strip shows at once (6–18)',
    setPianoWheelSpeed: 'Wheel speed', setPianoWheelSpeedHint: 'Rows scrolled per pixel (0.005–0.03); larger scrolls faster',
    setPianoSnapMs: 'Snap delay (ms)', setPianoSnapMsHint: 'Delay after the wheel stops before snapping to a whole row (100–400)',
    setLivePollMs: 'Poll interval (ms)', setLivePollMsHint: 'Live refresh interval (1500–10000); applies to the next live session',
    setLiveFollowPx: 'Follow threshold (px)', setLiveFollowPxHint: 'Distance from the bottom that still counts as "at bottom" and follows (20–120)',
    setLiveHistoryTurns: 'History turns kept', setLiveHistoryTurnsHint: 'History turns kept in live mode (0–10); applies to the next live session',
    setStallThresholdMin: 'Stall threshold (min)', setStallThresholdMinHint: 'Running but silent beyond this counts as likely stalled (1–10)',
    setRailEnhance: 'Enhance official turn navigator', setRailEnhanceHint: 'Overlay on the official right-side rail: conclusion section inside its preview card, right-click to open the workbench',
    setPianoClassic: 'Classic left strip', setPianoClassicHint: 'The plugin\'s own left turn strip (on by default, coexists with the official right rail; clicking an unloaded turn delegates to the official auto-load navigation)',
    setRailHide: 'Hide official turn navigator', setRailHideHint: 'Fully hide the official right-side rail and keep only our strip (the rail enhancement is inert while this is on)',
    railMetaCalls: '{tools} tools', railMetaErrors: '{errors} errors', railThinking: 'thinking',
    setSave: 'Save', setDiscard: 'Discard', setSaveFail: 'Some settings were not saved — check and retry',
    setReset: 'Reset', setOverridden: 'Modified', setInvalid: 'Out of range or invalid format',
    setUnavailable: 'The settings service is not exposed in this environment (upgrade dsh and retry)',
  }

export { STR }
